## MLflow Setup & Experiment
- **Tracking URI:** `file:///Users/zahra/Desktop/ChronusMLOps/mlruns`
- **Experiment:** `BaghdadRentalMonitoring`

## Model Loading – `BaghdadRentalModel` (v2)
- **Model Run ID:** `712145214163613216/fd0954aceff7401c8ed535e335b259de`
- **Source Data:** `rent_v7.csv` (cleaned, dates dropped)
- **Version:** 2 of `BaghdadRentalModel`

## Monitoring Run – April 29
- **Run Name:** `monitor_april_29`
- **RMSE:**  `{rmse:.2f}`  |  **R²:** `{r2:.2f}`
- **Tag:** `source = rent_v7_tail`

## Prediction Results
- **Columns:** `y_true`, `y_pred`, `error`

In [4]:

import pandas as pd
import mlflow
import mlflow.sklearn
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
import joblib
import numpy as np

mlflow.set_tracking_uri("file:///Users/zahra/Desktop/ChronusMLOps/mlruns")
mlflow.set_experiment("BaghdadRentalMonitoring")

model_path = "/Users/zahra/Desktop/ChronusMLOps/mlruns/712145214163613216/fd0954aceff7401c8ed535e335b259de/artifacts/model"
model = mlflow.sklearn.load_model(model_path)

df = pd.read_csv("../data/interim/rent_v7.csv")
X = df.drop(columns=["final_rent_price_usd"])
y = df["final_rent_price_usd"]

X_new = X.tail(10)
y_true = y.tail(10)

y_pred = model.predict(X_new)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
r2 = r2_score(y_true, y_pred)

with mlflow.start_run(run_name="monitor_april_29"):
    mlflow.log_metric("rmse", rmse)
    mlflow.log_metric("r2", r2)
    mlflow.set_tag("source", "rent_v7_tail")
    print(f"\n✅ Logged monitoring run: RMSE={rmse:.2f}, R²={r2:.2f}")

results = pd.DataFrame({
    "y_true": y_true.values,
    "y_pred": y_pred,
    "error": y_pred - y_true.values
})

results

✅ Logged monitoring run: RMSE=342.16, R²=0.73

        y_true       y_pred       error
0  2000.000000  1766.016195 -233.983805
1  1333.333333  1670.961313  337.627979
2   666.666667   862.646042  195.979375
3  2900.000000  2068.926284 -831.073716
4   773.333333  1072.248655  298.915322
5   500.000000   629.515657  129.515657
6  1293.868333  1089.679235 -204.189099
7  1293.868333  1089.679235 -204.189099
8  1293.868333  1089.679235 -204.189099
9  1293.868333  1089.679235 -204.189099